# Generated by Django 4.1.4 on 2022-12-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionImage', models.ImageField(upload_to='quiz_images', verbose_name='Image')),
                ('answer1', models.CharField(max_length=100, verbose_name='Answer 1')),
                ('answer2', models.CharField(max_length=100, verbose_name='Answer 2')),
                ('answer3', models.CharField(max_length=100, verbose_name='Answer 3')),
                ('answer4', models.CharField(max_length=100, verbose_name='Answer 4')),
                ('answers', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4)], default=False, max_length=30, verbose_name='Correct answer is')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
    ]
